### ISSUE TITLE
Why was this project abandoned?

### ISSUE THREAD

**Issue by ca0v** [WSDOT-GIS/Traveler-Info-GeoServices-REST#2]
Did you find another solution or did you find that it was just too much work for the time you had available?  What were the challenges?  Can you give some warnings and insights into someone wanting to attempt this same thing?

**Comment by JeffJacobson** [comment]
I found it was much easier to call the [API] directly from a client application and then convert the JSON response it returned to whatever format was required than it was to create and maintain a separate server application to do the conversion.

[API]:http://www.wsdot.wa.gov/Traffic/api/
